# Generated by Django 4.0.4 on 2022-05-17 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllVaccination',
            fields=[
                ('name_disease', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('need_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nick_animal', models.CharField(max_length=100)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField(null=True)),
                ('zoo_name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='m', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('number_cell', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('square_cell', models.IntegerField()),
                ('access_to_com_room', models.BooleanField()),
                ('date_in_cell', models.DateTimeField(null=True)),
                ('date_out_cell', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_start_work', models.DateTimeField()),
                ('gender', models.CharField(max_length=100)),
                ('date_birthday', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GetEmployeeList',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('can_in_cell', models.BooleanField()),
                ('salary', models.IntegerField()),
                ('main_atribute', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name_supplier', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('name_korm', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('date_supplies', models.DateTimeField(null=True)),
                ('qua_product', models.IntegerField()),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='TypeAnimal',
            fields=[
                ('type_animal', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('climate_zone', models.CharField(max_length=100)),
                ('type_food', models.CharField(max_length=100)),
                ('need_warm_summer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EnemyAnimals',
            fields=[
                ('type_animal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.typeanimal')),
                ('type_enemy_animal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FriendsAnimals',
            fields=[
                ('type_animal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.typeanimal')),
                ('type_friend_animal', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.animal')),
                ('date_inspection', models.DateTimeField()),
                ('width_animal', models.CharField(max_length=100)),
                ('height_animal', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('type_food', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('name_korm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.supplies')),
            ],
        ),
        migrations.CreateModel(
            name='Supervisors',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('animal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.animal')),
                ('name_people', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='id_prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.profession'),
        ),
        migrations.CreateModel(
            name='EatWinter',
            fields=[
                ('id_food', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number_of_feedings', models.IntegerField()),
                ('time_feedings', models.IntegerField()),
                ('qua_in_kg', models.IntegerField()),
                ('type_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typefood', to_field='name_korm_id')),
            ],
        ),
        migrations.CreateModel(
            name='EatSummer',
            fields=[
                ('id_food', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('number_of_feedings', models.IntegerField()),
                ('time_feedings', models.IntegerField()),
                ('qua_in_kg', models.IntegerField()),
                ('type_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typefood', to_field='name_korm_id')),
            ],
        ),
        migrations.CreateModel(
            name='EatCharact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('condition', models.CharField(max_length=100)),
                ('max_height', models.IntegerField()),
                ('max_width', models.IntegerField()),
                ('min_width', models.IntegerField()),
                ('min_height', models.IntegerField()),
                ('food_summer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eatsummer')),
                ('food_winter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eatwinter')),
                ('type_animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typeanimal')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id_disease', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name_disease', models.CharField(max_length=100)),
                ('start_of_disease', models.DateTimeField()),
                ('end_of_disease', models.DateTimeField(null=True)),
                ('id_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.animal')),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='cur_supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.eatcharact'),
        ),
        migrations.AddField(
            model_name='animal',
            name='numb_cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.cell'),
        ),
        migrations.AddField(
            model_name='animal',
            name='type_animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.typeanimal'),
        ),
        migrations.CreateModel(
            name='DoneVaccination',
            fields=[
                ('id_card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.animal')),
                ('date_vaccination', models.DateTimeField()),
                ('name_disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.allvaccination')),
            ],
        ),
    ]
